[versions]
agp = "8.13.2"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.2"
constraintlayout = "2.2.1"
gson = "2.10.1"
poi = "5.2.5"
pdfbox = "2.0.27.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
poi = { group = "org.apache.poi", name = "poi", version.ref = "poi" }
poi-ooxml = { group = "org.apache.poi", name = "poi-ooxml", version.ref = "poi" }
poi-ooxml-full = { group = "org.apache.poi", name = "poi-ooxml-full", version.ref = "poi" }
poi-scratchpad = { group = "org.apache.poi", name = "poi-scratchpad", version.ref = "poi" }
pdfbox = { group = "com.tom-roush", name = "pdfbox-android", version.ref = "pdfbox" }
log4j-to-slf4j = { group = "org.apache.logging.log4j", name = "log4j-to-slf4j", version = "2.24.1" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version = "2.0.12" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
